robot_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
four_wheel_steering_controller:
  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['front_left_wheel', 'front_right_wheel']
  rear_wheel: ['rear_left_wheel', 'rear_right_wheel']
  front_steering: ['Left_wheel_03_link', 'Right_wheel_03_link']
  rear_steering: ['Left_wheel_01_link', 'Right_wheel_01_link']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 25.0 # not tested here

  # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true
